GET localhost:8080/api/subgoals/1

###
POST localhost:8080/api/goals
Content-Type: application/json

{
  "title": "goal1",
  "desc": "desc",
  "userId": "1",
  "category": "English"
}

###

POST localhost:8080/api/subgoals
Content-Type: application/json

{
  "title": "subgoal1",
  "desc": "desc",
  "goalTitle": "goal1"
}

###
